apiVersion: v1
kind: Service
metadata:
  name: postgres-targeting-service-deployment
  namespace: toggle-master
  labels:
    app: postgres-targeting-service-deployment
spec:
  type: ClusterIP
  selector:
    app: postgres-targeting-service-deployment
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
