name: Targeting Service CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - aws-cloud-k8s

permissions:
  contents: read
  id-token: write

jobs:
  ci:
    name: Targeting Service CI

    uses: astronomaelaine/CI-reusable-source-py/.github/workflows/ci-reusable.yml@main

    permissions:
      contents: read
      id-token: write

    with:
      aws-region: ${{ vars.AWS_REGION }}
      aws-role-arn: ${{ vars.AWS_ROLE_ARN }}
      ecr-repository: ${{ vars.ECR_REPOSITORY }}
      image-name: "targeting-service"
      app-version: ${{ vars.APP_VERSION }}


  gitops-update:
    name: Update GitOps Image

    needs:
      - ci

    if: >
      github.event_name == 'push' &&
      github.ref == 'refs/heads/aws-cloud-k8s'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitOps repository
        uses: actions/checkout@v6
        with:
          repository: ramondata/toggle-master-gitops
          ref: master
          ssh-key: ${{ secrets.GITOPS_DEPLOY_KEY }}
          path: gitops

      - name: Update targeting-service image tag
        env:
          IMAGE_TAG: ${{ needs.ci.outputs.image-tag }}
        run: |
          cd gitops

          sed -i -E \
            "s|^  tag:.*|  tag: ${IMAGE_TAG}|" \
            apps/targeting-service/values.yaml

          echo "New image tag:"
          grep -A2 "^image:" apps/targeting-service/values.yaml

      - name: Commit GitOps change
        env:
          IMAGE_TAG: ${{ needs.ci.outputs.image-tag }}
        run: |
          cd gitops

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add apps/targeting-service/values.yaml

          if git diff --cached --quiet; then
            echo "No GitOps changes detected"
            exit 0
          fi

          git commit -m "chore(targeting-service): deploy ${IMAGE_TAG}"
          git push origin master
